### ISSUE TITLE
希望可以完善一下API文档，新手碰壁有点多

### ISSUE THREAD

**Issue by mqllin** [wechaty/puppet-xp#48]
本人比较菜，用了2天时间解决各种npm i中报的错误（项目要求python2.7环境这点花费了最长的时间去探索），在提供的“ding-dong”demo中尝试调用了几个方法如messageSendUrl(),又或是msg.say(FileBoxInterface)都没能成功调用不是报错就是无反应。可能我还不能很好的区分wechaty 的API和puppet API 的区别，再比如 puppet-xp/ripe-wechaty.ts中的msg.wechaty.wrapAsync()方法在文档之中也没能查到是起到了什么效果。希望可以提供一个对于新手更为友好puppet-xp框架的开发文档。🙏🙏🙏

**Comment by mqllin** [comment]
而且npm淘宝镜像不能正确完成npm install 操作（有的包下载不到），这一点在[getting-started](https://github.com/wechaty/getting-started)中有误导新手的嫌疑。

**Comment by atorber** [comment]
> 本人比较菜，用了2天时间解决各种npm i中报的错误（项目要求python2.7环境这点花费了最长的时间去探索），在提供的“ding-dong”demo中尝试调用了几个方法如messageSendUrl(),又或是msg.say(FileBoxInterface)都没能成功调用不是报错就是无反应。可能我还不能很好的区分wechaty 的API和puppet API 的区别，再比如 puppet-xp/ripe-wechaty.ts中的msg.wechaty.wrapAsync()方法在文档之中也没能查到是起到了什么效果。希望可以提供一个对于新手更为友好puppet-xp框架的开发文档。🙏🙏🙏

@mqllin  we are glad to see that you are interested in XP project. XP is a young open source project, and the documentation is not perfect enough. You are welcome to contribute your own code help  puppet-xp to improve the document.
And, in order to better use wchaty, I recommend you to learn the official documents of wechaty https://wechaty.js.org/  to understand the relationship between puppet and wechaty, and the complete interface usage methods.
For exceptions, you can refer to the readme documentation of project puppet-xp to check the interfaces that XP already supports.

**Comment by zhihualipolestar** [comment]
安装readme里exe就可以了吗？还需要dll注入吗？

**Comment by atorber** [comment]
> 
STEP 1: Install wechat client in your Windows computer.
STEP 2: Login the wechat client on the computer.
STEP 3: Getting Started with TypeScript/JavaScript (RECOMMENDED).

You can see the readme document of the project to get the usage.

**Comment by mqllin** [comment]
> 

安装文档中所指定的微信版本即可。启动并登录微信后，运行项目即可。不需要去关心注入的问题。

**Comment by mqllin** [comment]
> 安装readme里exe就可以了吗？还需要dll注入吗？

安装文档中所指定的微信版本即可。启动并登录微信后，运行项目即可。不需要去关心注入的问题。
